// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Compress executes native Go backend compression powered by engine (Jpegli, AVIF, WebP, PNG)
 */
export function Compress(task: $models.CompressTask): $CancellablePromise<$models.CompressResult> {
    return $Call.ByID(1799778128, task);
}

/**
 * ExportZip creates a zip archive of the specified files
 */
export function ExportZip(files: string[] | null, defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(1739744113, files, defaultName);
}

/**
 * GetSampleImage writes sample-dog.jpg to temp folder and returns its ImageItem
 */
export function GetSampleImage(): $CancellablePromise<$models.ImageItem> {
    return $Call.ByID(2126601567);
}

/**
 * RevealInFinder reveals the target path in Finder or File Explorer
 */
export function RevealInFinder(targetPath: string): $CancellablePromise<void> {
    return $Call.ByID(1628441990, targetPath);
}

/**
 * ScanFiles scans given file paths or directory paths and returns valid ImageItem list
 */
export function ScanFiles(paths: string[] | null): $CancellablePromise<$models.ImageItem[] | null> {
    return $Call.ByID(1864949816, paths);
}

/**
 * SelectDirectory prompts user to select a folder
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2357884079);
}

/**
 * SelectFiles prompts user to select image files
 */
export function SelectFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1944964147);
}
