// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ImageService from "./imageservice.js";
export {
    ImageService
};

export type {
    CompressResult,
    CompressTask,
    ImageItem
} from "./models.js";
