// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CompressResult {
    "id": string;
    "success": boolean;
    "error"?: string;
    "inputPath": string;
    "outputPath": string;
    "originalSize": number;
    "compressedSize": number;
    "originalWidth": number;
    "originalHeight": number;
    "compressedWidth": number;
    "compressedHeight": number;
    "targetFormat": string;
    "durationMs": number;
}

export interface CompressTask {
    "id": string;
    "spaceId": string;
    "inputPath": string;
    "outputDir": string;
    "originalOutput": boolean;
    "suffix": string;

    /**
     * "original", "webp", "avif", "jpeg", "png"
     */
    "format": string;

    /**
     * 10 - 100
     */
    "quality": number;

    /**
     * "none", "width", "height", "scale", "fit"
     */
    "resizeMode": string;
    "width": number;
    "height": number;
    "scale": number;
    "keepExif": boolean;
}

export interface ImageItem {
    "id": string;
    "path": string;
    "name": string;
    "size": number;
    "width": number;
    "height": number;
    "format": string;
    "isDir": boolean;
}
